# Generated by Django 4.2.11 on 2024-12-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('rated', models.CharField(blank=True, max_length=10, null=True)),
                ('released', models.CharField(blank=True, max_length=20, null=True)),
                ('runtime', models.CharField(blank=True, max_length=20, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('writer', models.CharField(blank=True, max_length=255, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('poster', models.URLField(blank=True, null=True)),
                ('metascore', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb_votes', models.CharField(blank=True, max_length=20, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20, null=True)),
                ('dvd', models.CharField(blank=True, max_length=20, null=True)),
                ('box_office', models.CharField(blank=True, max_length=20, null=True)),
                ('production', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
